learning_templates/basic_app/urls.py
from django.conf.urls import url, include
from . import views

# TEMPLATE TAGGING, global name
app_name = 'basic_app'
urlpatterns = [
    url(r'^relative/$', views.relative_url_templates, name='relative'),
    url(r'^other/$', views.other, name='other')
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import include, path
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative_url_templates(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'index' %}">BRAND
          <span class="sr-only">(current)</span>
        </a>
        <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
        <a class="nav-item nav-link" href="{% url 'basic_app:other' %}">Other</a>

      </div>
  </nav>

  <div class="container ">
    {% block body_block %}
    <!-- Anything otside of this will be iherited if you extend -->
    {% endblock %}
  </div>
</body>

</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html> {% extends "basic_app/base.html" %} {% block body_block %}
<h1> WELCOME TO INDEX</h1>
<h2>This is index i</h2>
{{ text|cut:'hello' }} {{ text|upper }} {{ number|add:"2"}} {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html> {% extends "basic_app/base.html" %} {% block body_block %}
<h1> WELCOME TO OTHER</h1>
<h2>This is an example of template ihnheratance</h2>
{% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <h1> WELCOME TO RELATIVE URL TEMPLATES</h1>
  <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
  <a href="{% url 'admin:index' %}">ADMIN</a>
  <a href="{% url 'index' %}">MAIN </a>
</body>

</html>